# Generated by Django 6.0.3 on 2026-05-02 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_last_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrator"),
                    ("moderator", "Moderator"),
                    ("user", "Użytkownik"),
                ],
                default="user",
                max_length=20,
            ),
        ),
    ]
